# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # Salt Server - CentOS 8.x
  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-8"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.99.100"
    server.vm.provision "shell", path: "scripts/add_hosts.sh"
	  server.vm.provision "shell", path: "scripts/centos/add_packages_centos.sh"
	  server.vm.provision "shell", path: "scripts/centos/salt/create-master-salt.sh"
    server.vm.synced_folder "vagrant/", "/vagrant"
    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
    end
  end
  
  # Salt Client #1 - CentOS 8.x
  config.vm.define "web1" do |web1|
    web1.vm.box = "shekeriev/centos-stream-8"
    web1.vm.hostname = "client-web-1"
    web1.vm.network "private_network", ip: "192.168.99.101"
    web1.vm.provision "shell", path: "scripts/add_hosts.sh"
	  web1.vm.provision "shell", path: "scripts/centos/add_packages_centos.sh"
	  web1.vm.provision "shell", path: "scripts/centos/salt/create-minion.sh"
    web1.vm.synced_folder "vagrant/", "/vagrant"
    web1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end

  # Salt Client #2 - Debian 11
  config.vm.define "web2" do |web2|
    web2.vm.box = "shekeriev/debian-11"
    web2.vm.hostname = "client-web-2"
    web2.vm.network "private_network", ip: "192.168.99.102"
    web2.vm.provision "shell", path: "scripts/add_hosts.sh"
	  web2.vm.provision "shell", path: "scripts/debian/add_packages_debian.sh"
	  web2.vm.provision "shell", path: "scripts/debian/salt/create-minion.sh"
    web2.vm.synced_folder "vagrant/", "/vagrant"
    web2.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end
  
  # Salt Client #3 - CentOS 8.x
  config.vm.define "db1" do |db1|
    db1.vm.box = "shekeriev/centos-stream-8"
    db1.vm.hostname = "client-db-1"
    db1.vm.network "private_network", ip: "192.168.99.103"
    db1.vm.provision "shell", path: "scripts/add_hosts.sh"
	  db1.vm.provision "shell", path: "scripts/centos/add_packages_centos.sh"
	  db1.vm.provision "shell", path: "scripts/centos/salt/create-minion.sh"
    db1.vm.synced_folder "vagrant/", "/vagrant"
    db1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end

  # Salt Client #4 - Debian 11
  config.vm.define "db2" do |db2|
    db2.vm.box = "shekeriev/debian-11"
    db2.vm.hostname = "client-db-2"
    db2.vm.network "private_network", ip: "192.168.99.104"
    db2.vm.provision "shell", path: "scripts/add_hosts.sh"
	  db2.vm.provision "shell", path: "scripts/debian/add_packages_debian.sh"
	  db2.vm.provision "shell", path: "scripts/debian/salt/create-minion.sh"
    db2.vm.synced_folder "vagrant/", "/vagrant"
    db2.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end

  config.trigger.after :up do |trigger|
        trigger.only_on = "db2"
        trigger.info = "* Register Salt Minions"
        trigger.run = {inline: "vagrant ssh -c 'sudo salt-key -A -y' server"}
  end 
  
end
