- name: "Install Software - RedHat"
  yum:
    name: "{{item}}"
    state: present
  with_items: 
    - mariadb-server

- name: "Enable MariaDb - RedHat"
  service:
    name: mariadb.service
    enabled: yes
    state: restarted

- name: Allow DB service in the firewall
  firewalld:
    port: 3306/tcp
    permanent: yes
    immediate: yes
    state: enabled


