- name: Prep yum
  apt:
    name: yum-utils
    state: present
- name: Create Docker Repository
  apt_repository:
    description: Docker Repository
    name: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: true
- name: Install Docker
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Installing Docker Service
  service:
    name: docker
    state: started