global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['monitoring:9090']
  - job_name: 'kafka-hosts'
    static_configs:
    - targets: ['kafka-1:9100']
    - targets: ['kafka-2:9100']
    - targets: ['kafka-3:9100']
  - job_name: 'kafka-jmx'
    static_configs:
    - targets: ['kafka-1:9101']
    - targets: ['kafka-2:9101']
    - targets: ['kafka-3:9101']
